### ISSUE TITLE
Not working on low level recipe?

### ISSUE THREAD

**Issue by vkyfox** [infiniteWander/xiv_gui_solver#2]
Adding this recipe to the yaml, which is the exact values for the craft as per https://yyyy.games/crafter/#/simulator and seem to make sense with the rest of the recipe ; the software cannot solve.
```yaml
Lvl88: [1650, 7000, 40, 128, 112, 100, 100]
```

**Comment by Malphaet** [comment]
The crashing is alarming, however the result doesn't seem to be wrong ?
I mean solutions exists but they are so trivial that the solver can't find them with the default parameters.
Using byregot step 6 (or --long) and depth 11 ( -D/--desperate) and desperate will solve it easily
However the gui doesn't have those modes as a failsafe soooo.... more rewriting ...

**Comment by Malphaet** [comment]
099ea3fcbaff4672a94cf33680d58e601d235c02 Should resolve the issue
